version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - .docker/conf/nginx/info.conf:/etc/nginx/conf.d/info.conf

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: magento
    env_file:
      - mysql.env
        
  php:
    build:
      context: ./.docker/build/context/php
      network: host
    volumes:
      - ./src:/src
